# Copyright (c) 2026 Graphcore Ltd. All rights reserved.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    pull-request-branch-name:
      separator: "-"
    groups:
      actions-by-dependency:
        group-by: dependency-name

  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    pull-request-branch-name:
      separator: "-"
    groups:
      # Group multiple updates together into a single PR
      non-major:
        update-types: ["minor", "patch"]
