# Copyright (c) 2026 Graphcore Ltd. All rights reserved.
# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_stages = ["pre-commit", "pre-merge-commit"]
default_install_hook_types = ["commit-msg", "pre-commit", "pre-merge-commit"]

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-added-large-files"
priority = 4

[[repos.hooks]]
id = "check-case-conflict"
priority = 4

[[repos.hooks]]
id = "check-executables-have-shebangs"
priority = 4

[[repos.hooks]]
id = "check-merge-conflict"
priority = 4

[[repos.hooks]]
id = "check-toml"
priority = 4

[[repos.hooks]]
id = "check-yaml"
priority = 4

[[repos.hooks]]
id = "end-of-file-fixer"
priority = 3

[[repos.hooks]]
id = "mixed-line-ending"
exclude = "licenses.html"
priority = 2

[[repos.hooks]]
id = "trailing-whitespace"
exclude = "licenses.html"
priority = 1

[[repos]]
repo = "local"

[[repos.hooks]]
id = "check-copyright"
name = "check copyright"
description = "check copyright notice is valid"
language = "system"
entry = "cargo run --bin check-copyright"
require_serial = true
exclude = '''
(?x)(
  ^.git/.*|
  ^Cargo.lock|
  .*\.stderr$|
  d3.*.js|
  jquery.*.js|
  .*\.png|
  .*\.json
)
'''
priority = 4

[[repos.hooks]]
id = "lychee-check-links"
name = "check links"
description = "check validity of links in Markdown and HTML"
language = "system"
types_or = ["html", "markdown"]
entry = "lychee ."
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "taplo-fmt"
name = "taplo fmt"
description = "check syntax and formatting of TOML files"
language = "system"
types = ["toml"]
entry = "taplo fmt --diff"
priority = 0

[[repos.hooks]]
id = "prettier-markdown"
name = "prettier markdown"
description = "check formatting of Markdown files"
language = "system"
types = ["markdown"]
entry = "npx prettier --write"
priority = 0

[[repos.hooks]]
id = "prettier-yaml"
name = "prettier yaml"
description = "check formatting of YAML files"
language = "system"
types = ["yaml"]
entry = "npx prettier --write"
priority = 0

[[repos.hooks]]
id = "cargo-deny"
name = "cargo deny"
description = "check Rust dependencies licenses and for vulnerabilities"
language = "system"
types_or = ["rust", "toml"]
entry = "cargo deny check"
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "cargo-about"
name = "cargo about"
description = "Document licenses of Rust dependencies"
language = "system"
types_or = ["rust", "toml"]
entry = "cargo about generate --locked --workspace --all-features --fail --config about.toml --output-file licenses.html about.hbs"
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "cargo-nightly-fmt"
name = "cargo +nightly fmt"
description = 'format files with "cargo fmt" from the nightly toolchain'
language = "system"
types = ["rust"]
entry = "cargo +nightly fmt --"
priority = 0

[[repos.hooks]]
id = "cargo-check"
name = "cargo check"
description = "check for package errors with cargo check"
language = "system"
types_or = ["rust", "toml"]
entry = "cargo check --all-targets"
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "cargo-clippy-strict"
name = "cargo clippy-strict"
description = "lint Rust source code"
language = "system"
types = ["rust"]
entry = 'env RUSTFLAGS="-D warnings" cargo clippy-strict'
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "cargo-doc-gwr-dev"
name = "cargo doc-gwr-dev"
description = "check Rust source code documentation"
language = "system"
types = ["rust"]
entry = 'env RUSTDOCFLAGS="-D warnings" cargo doc-gwr-dev'
pass_filenames = false
priority = 4

[[repos.hooks]]
id = "cargo-semver-checks"
name = "cargo semver-checks"
description = "lint crate API changes for semver violations"
language = "script"
types_or = ["rust", "toml"]
entry = "semver-checks.sh"
pass_filenames = false
priority = 4
stages = ["manual"]

[[repos.hooks]]
id = "cog-verify"
name = "cog verify"
description = "check commit message is in Conventional Commit form"
language = "system"
entry = "cog verify --file"
priority = 0
stages = ["commit-msg"]
