# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

name: Cached semver check access
description: The semantic version check build directory paths and key to be used when caching

outputs:
  paths:
    description: The cached build paths
    value: ${{ steps.get-paths.outputs.cached-build-paths }}

  key:
    description: The generated cached build key
    value: ${{ steps.generate-key.outputs.cached-build-key }}

runs:
  using: composite
  steps:
    - id: get-paths
      run: |
          echo 'cached-build-paths<<EOF' >> $GITHUB_OUTPUT
          echo 'target/semver-checks'>> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      shell: bash

    - id: generate-key
      run: echo "cached-build-key=${{ runner.os }}-cargo-steam-semver-${{ hashFiles('**/Cargo.lock') }}" >> $GITHUB_OUTPUT
      shell: bash
