# Copyright (c) 2025 Graphcore Ltd. All rights reserved.

name: Install dev dependencies
description: Install all dependencies required when developing the repo source

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-dev-deps-${{ hashFiles('./.github/actions/install-dev-dependencies/**') }}
        restore-keys: |
          ${{ runner.os }}-cargo-dev-deps-
          ${{ runner.os }}-cargo-build-deps-

    - name: Run install.sh
      run: ./.github/actions/install-dev-dependencies/install.sh
      shell: bash
